# Generated by Django 2.2.7 on 2019-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=23)),
                ('user_pass', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=39)),
                ('group_id', models.IntegerField()),
                ('state', models.PositiveIntegerField()),
                ('unban_time', models.PositiveIntegerField()),
                ('expiration_time', models.PositiveIntegerField()),
                ('logincount', models.PositiveIntegerField()),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('character_slots', models.PositiveIntegerField()),
                ('pincode', models.CharField(max_length=4)),
                ('pincode_change', models.PositiveIntegerField()),
                ('vip_time', models.PositiveIntegerField()),
                ('old_group', models.IntegerField()),
            ],
            options={
                'db_table': 'login',
                'managed': True,
            },
        ),
    ]
