# Generated by Django 2.2.7 on 2019-11-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
    ]
