# Generated by Django 2.2.7 on 2019-11-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191119_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': True},
        ),
    ]
