# Generated by Django 2.2.7 on 2019-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191119_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
