# Generated by Django 2.2.7 on 2019-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191119_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='expiration_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='logincount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='unban_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
