# Generated by Django 2.2.7 on 2019-11-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191119_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='character_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='old_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='pincode_change',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='login',
            name='vip_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
