# Generated by Django 2.2.7 on 2019-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191119_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_full', models.TextField(blank=True, default='', null=True)),
                ('link_patch', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
