# Generated by Django 2.2.7 on 2019-11-22 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_downloadlinkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 22, 16, 24, 38, 630040, tzinfo=utc))),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 22, 16, 39, 38, 630067, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Login')),
            ],
        ),
    ]
