# Generated by Django 2.2.7 on 2019-11-22 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 16, 25, 12, 731514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 22, 16, 40, 12, 731543, tzinfo=utc), null=True),
        ),
    ]
