# Generated by Django 2.2.7 on 2019-11-28 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191122_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 16, 10, 30, 887234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 28, 16, 25, 30, 887259, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
